### PR TITLE
Interactive list

### PR DESCRIPTION
**Pull request by PolinaStamenova**
###  #Drag $ drop functionality, checkboxes 

**JavaScript:**
- Add drag$drop.js.
- Add status.js

_Thank you for taking the time to review my PR!_ 🌵 😄

### CODE REVIEW

**Review by Dipeshtwis — COMMENTED** [review]
## HI @PolinaStamenova,
# Status: Invalid ❌

Please fix the issue mentioned below and then request for code review

## Reason

- [ ] Please setup the JS and CSS linters.

### Please make sure to submit code review when you are done with the changes that was requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

**_Dipesh Kumar_**

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
Hi @PolinaStamenova, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: It has event listeners on the list items (`dragstart`, `dragover`, `drop`) and to checkbox (`change`).
:+1: The task object's values for `index` and `completed` are updated upon user actions.
:+1: The updated array of items is stored in local storage.

Good job so far!
There are some general issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [ ] README file should have description about the project even if it's one or two line so that anyone can understand about your project.
- [ ] The live link currently showing the readme of the project. Please fix this. Also there is a typo on line no. 39 in README file. It should be `npm start` instead of `npm star`.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by PolinaStamenova** [comment]
Solved issues!

**Review by DeliceLydia — APPROVED** [review]
# Congratulations🎉 🎉 

## Hi @PolinaStamenova, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
